### ISSUE TITLE
backpressure surge events can create holes with holium

### ISSUE THREAD

**Issue by Darkmajia** [impstation/imp-station-14#1038]
## Description
this reagent must die

**Reproduction**
witness round 2294 near telecomms in engineering

**Comment by hivehum** [comment]
what do you MEAN backpressure surge doesnt have a blacklist

**Comment by kipdotnet** [comment]
Would you consider "this is really really really funny" as a counterpoint

**Comment by hivehum** [comment]
yeah also briefly looking into it, this has a VERY rare chance of actually happening. the correct way to fix this would probably be to implement a blacklist to ventclogrule but honestly i do think its funny enough not to fix

**Comment by hivehum** [comment]
i do think it would be better to implement a blacklist to the event rule rather than remove holium entirely. its fine for its intended purpose and i think it sucks to remove it because one event has a commented todo instead of properly filtering what reagents it  can select

**Comment by hivehum** [comment]
![Code_WCn2h2COkF](https://github.com/user-attachments/assets/30001a0b-c2aa-48c4-b41b-3464185ca0b3)

**Comment by TheGrimbeeper** [comment]
This was resolved in #1050. Can be closed,
