### ISSUE TITLE
unisex species that weren't unisex before only have the classic bra undershirt

### ISSUE THREAD

**Issue by Hikkikira** [impstation/imp-station-14#1102]
## Description

**Reproduction**

make a unisex character that's non spider and has undershirts available

**Screenshots**

![image](https://github.com/user-attachments/assets/3b89cf8e-dd38-4661-8229-7be1d15c1423)

**Additional context**

'were not unisex before' as in they didn't have that option until it was changed it for imp which is I guess why this happens??

**Comment by DinnerCalzone** [comment]
This should now be fixed with PR  #1115
