### ISSUE TITLE
Animated items embedded in revenants continue to attack even after the revenant dematerializes.

### ISSUE THREAD

**Issue by ATDoop** [impstation/imp-station-14#1169]
## Description
If an item gets embedded in a revenant, and then it animates the item, the item will continue to attack even after the revenant disappears.

**Reproduction**
1. Throw skewer at manifested revenant.
2. Revenant animates skewer
3. Revenant disappears
4. Skewer continues attacking even though it is now invisible.

**Comment by TGRCdev** [comment]
What the fuck lmao
