### ISSUE TITLE
ghost bar affecting kill/survive objectives in endround

### ISSUE THREAD

**Issue by mqole** [impstation/imp-station-14#488]
## Description
if you die and respawn at the ghostbar, anyone with an objective to kill you will have you show up as alive, and fail that objective. this isnt the case for "get to centcomm" iirc but it does affect "make sure your fellow traitor survives".

also seen people getting confused when they check their c menu and see that the guy they gibbed is apparently completely fine

**Comment by formlessnameless** [comment]
Working on a ghost bar pr
