### ISSUE TITLE
ghost bar message too long

### ISSUE THREAD

**Issue by hivehum** [impstation/imp-station-14#490]
## Description
you can click drag to reveal the rest but like this is really ugly/jank looking

**Reproduction**
press the button to join the ghost bar. be repulsed

**Screenshots**
![SS14 Loader_GWyX1BQjkV](https://github.com/user-attachments/assets/22906094-a236-42d2-aa34-0a523b3b4cbe)

**Additional context**

**Comment by formlessnameless** [comment]
Working on a ghost bar pr
