### ISSUE TITLE
re-rotate origin please

### ISSUE THREAD

**Issue by hivehum** [impstation/imp-station-14#504]
## Description

anything to keep us from rolling box and meta on repeat at 50+ pop. please. please. please

**Comment by mqole** [comment]
probably no longer an issue now that we have union barratry xeno and hummingbird

**Comment by DinnerCalzone** [comment]
If there is a list of known issues with Origin for why it got derotated (besides reducing maintaner load upstream), I would be willing to look into fixing and adding it back in.

**Comment by hivehum** [comment]
i wrote up something briefly when mq looked into it. let me see

origin doesnt have AI
and i think it may have the same problems atlas did (no lv wiring for atmos pipes at the very least)
so cameras need to be redone and the wiring in engineering would need to be checked

**Comment by DinnerCalzone** [comment]
AI cameras my beloathed. Yeah I can work on that.

**Comment by DinnerCalzone** [comment]
This issue has been addressed as of PR #923 and can be closed.

**Comment by hivehum** [comment]
my beloved origin
