### ISSUE TITLE
Replace art of Sam Grimm in the game lobby

### ISSUE THREAD

**Issue by ghostphasemoon** [impstation/imp-station-14#511]
Requesting the current art of my character to be updated to reflect his character more accurately

([ linked is where the webp file can be found](https://drive.google.com/file/d/1C86FaChk1WL4zbS9PKlgwaAHIERYjoAB/view?usp=sharing))

**Comment by TGRCdev** [comment]
Working on this rn. Just double-checking to make sure I'm not making any mistakes:
- Are you are the artist of that image?
- If so, do you still wish to license it under [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.en), the same license as the previous lobby art?

**Comment by ghostphasemoon** [comment]
- Yes I am the original artist of the image.
- Yes I still wish to license it.
Thank you for checking in.
