### ISSUE TITLE
AI can get teleported by artifacts

### ISSUE THREAD

**Issue by TheGrimbeeper** [impstation/imp-station-14#515]
## Description

An AI can get teleported by an artifact teleporting a random person. This bricks the AI
**Reproduction**

Step 1: Have an AI player
Step 2: Have an artifact with the effect 'EffectPortal' (randomly selects a player and teleports them to the artifact)
Step 3: trigger the effect until the AI is teleported. have as little other players around to maximise chance that AI is selected
**Screenshots**

**Additional context**

Likely an issue upstream. Needs upstream/downstream testing.

**Comment by formlessnameless** [comment]
There's a PR upstream for this, I'll look into merging it
