### ISSUE TITLE
re-implement drones

### ISSUE THREAD

**Issue by Darkmajia** [impstation/imp-station-14#516]
## Description
drones were removed upstream. maybe we can be trusted with them
removed in pr https://github.com/space-wizards/space-station-14/pull/25372, the ghost role is commented out in `Resources/Prototypes/Entities/Mobs/Player/silicon.yml`

**Comment by hivehum** [comment]
i might be too stupid for this one but preliminary attempt at bringing back drones [is in this branch here ](https://github.com/impstation/imp-station-14/compare/master...hivehum:imp-station-14:drones)
