### ISSUE TITLE
Heretic can sacrifice all of their organs on accident

### ISSUE THREAD

**Issue by Mousetrinity** [impstation/imp-station-14#558]
With the ritual of knowledge, you get 4 random items required for a ritual. One of these can be "Organ", so just any organs. If you do the Ritual of Knowledge and it requires an organ, you can end up sacrificing every single organ in your body.
Specifically a fucked issue because you can't check the requirements for a ritual without attempting it, meaning it'll count the organs in your body as ready for the ritual and not list them, leading to unknowingly sacrificing every organ in your body.
The ritual will also take multiples of the same item for the ritual, so even with an organ outside of your body for the ritual, you may still end up sacrificing the organs in your own body (speculation).

**Reproduction**
- Unlock the Ritual of Knowledge
- Roll the requirements of Organ (or other organs)
- Complete the ritual
Congratulations, you've lost every organ in your body!

**Additional context**
Apparently a fix for this from Goob exists, Impstation just has to grab it. I'm just submitting this report to be sure it's not forgotten about ^^

**Comment by irismessage** [comment]
this is funny as fuck actually. some monkey's paw shit

**Comment by TGRCdev** [comment]
I'm pretty sure we fixed this in #673 but please reopen if it's still happening
