### ISSUE TITLE
reptiles no longer use the animal metabolism group

### ISSUE THREAD

**Issue by KingMudkipIII** [impstation/imp-station-14#624]
## Description
Reptiles got changed to have their own metabolism group when the thumper drink was added. this means theyre no longer poisoned by theobromine and are poisoned by animal proteins. Im personally suggesting that pr gets reverted unless someone wants to fix it

**Reproduction**

eat a rat as a reptile. enjoy the pain
**Screenshots**

**Additional context**

**Comment by LucasTheDrgn** [comment]
Turns out metabolizerTypes is a list so it literally was just adding "Animal, " in there #630

**Comment by TGRCdev** [comment]
If I'm reading this right, this should be fixed now
