### ISSUE TITLE
decapoid vaporizer tank 

### ISSUE THREAD

**Issue by widgetbeck** [impstation/imp-station-14#634]
## Description

Flotsam is working on the decapoid vaporizer tanks.
**Reproduction**

n/a
**Screenshots**

n/a
**Additional context**

vaporizer tanks should output at minimum 0.00437 mols of water vapor per second, probably a little more. unsure of the conversion rate from units to mols but i suspect it's irrelevant - it doesn't have to be perfectly efficient, it just has to be interesting for gameplay.

**Comment by TGRCdev** [comment]
Rough estimate of the number of moles required to breathe (thanks beck)
![image](https://github.com/user-attachments/assets/71f2f2c8-5288-4cf6-b4fa-04cc2e3c2aae)

Other notes:
- 30u water chamber
- Needs to be spillable if non-water substances get put in
