### ISSUE TITLE
SVS can roll on way lower pop than it should

### ISSUE THREAD

**Issue by kipdotnet** [impstation/imp-station-14#722]
## Description

SVS can roll on very low player count. 1823 had no security and only QM and HoP as command at roundstart. This did not go very well
**Reproduction**

View replay for round #1823
**Screenshots**

![image](https://github.com/user-attachments/assets/8a29ed04-ac65-4bf8-8a2e-b31840d4d93f)

**Comment by hivehum** [comment]
WHAT DO YOU MEAN IT ROLLS MIN POP 15
