### ISSUE TITLE
xeno cryopod is pusk

### ISSUE THREAD

**Issue by mqole** [impstation/imp-station-14#739]
## Description
![image](https://github.com/user-attachments/assets/eacadbd6-d3af-4695-b0be-5c294041555a)

look at this shit

the gas filter is the wrong way around

its filtering co2 into the cryopod and filtering out everything else, which means the pod will never get cold

im going to become the joker.

**Comment by Darkmajia** [comment]
just set it to filter oxygen :)

**Comment by DinnerCalzone** [comment]
I have addressed this issues in #878. This issue can now be closed.

**Comment by hivehum** [comment]
yay! yay! yay! (in 1 week upstream will merge xeno and we all explode)
