### ISSUE TITLE
barratry (and probably xeno) need brigmedic spawners

### ISSUE THREAD

**Issue by Darkmajia** [impstation/imp-station-14#744]
## Description
the issue is that barratry (and probably xeno) need brigmedic spawners
this is mostly a self-reminder to get it done later but if someone beats me to it, then someone beats me to it

**Comment by hivehum** [comment]
increase minpop for xeno to like 40 or 50 while you're at it

**Comment by DinnerCalzone** [comment]
I have addressed these issues in #878. This issue can now be closed.
