### ISSUE TITLE
Put the server's CVar settings into a configuration file within the repo

### ISSUE THREAD

**Issue by TGRCdev** [impstation/imp-station-14#851]
Currently, we are modifying CVars by adjusting the default values in the actual CVar definitions. This isn't maintainable, as any upstream changes will end up unintentionally overwriting these values. This recently resulted in space wind being unintentionally disabled.

Upstream currently defines their server configurations under [Resources/ConfigPresets](https://github.com/impstation/imp-station-14/tree/master/Resources/ConfigPresets), and I think we should do the same. This would also require someone with access to the server to set the server's configuration path.

**Comment by irismessage** [comment]
this seems like a good idea and I should have figured it out earlier, if you grab the relevant and public ones out of https://github.com/impstation/hosting-config-example/blob/main/ss14/impstation/config.toml and merge it then I'll point the server at that.

also, do we currently use server.rules_file for our fork rules? if not let's open another issue for that

**Comment by irismessage** [comment]
implemented
